= Kfz Haendler
Lukas Starka
1.0.0, 2021-09-25: Some notes
ifndef::imagesdir[:imagesdir: images]
//:toc-placement!:  // prevents the generation of the doc at this position, so it can be printed afterwards
:sourcedir: ../backend/src/main/java
:icons: font
:sectnums:    // Nummerierung der Überschriften / section numbering
:toc: left

//Need this blank line after ifdef, don't know why...
ifdef::backend-html5[]

// print the toc here (not at the default position)
//toc::[]

== Description

This is a microproject about a car salesman. There are currently four entities including a customer, a car, a salesman and one entity for managing bought cars. Each of these entites has a repository with functions to save, update, delete and find entries within an entry. There are also services for each entity with routes to every method and http files for performing the requests. Additionally there are also unit-tests for each entity, integration-tests with assertj-core for the repositories and system-tests using RESTassured for the endpoints.

== Class Diagram

[plantuml, cld, png, align=left]
----
include::plantuml/cld.puml[]
----
